### PR TITLE
feat(About): new /about page

### PR DESCRIPTION
**Pull request by raphodn**
### What

See #364

Take the content of the current homepage - https://prices.openfoodfacts.org - and move it to a new `/about` page

### Screenshot

image

### CODE REVIEW

**Comment by raphodn** [comment]
@raphael0202 I moved about 90% of the current about page
- I removed the section on private proofs
- I did some minor rewording (like renaming some "food prices" to generic "product prices")

**Comment by raphodn** [comment]
I'm not sure it's compatible. The content is now translatable in Crowdin, there can be any language.

Indexing is definitely a topic, but in an other issue ?

**Comment by raphael0202** [comment]
Nice work!
What language do we use by default if the user is not logged-in? The browser-defined language?

**Comment by raphodn** [comment]
> Nice work! What language do we use by default if the user is not logged-in? The browser-defined language?

I believe so ! though this could would need some second eyes because it's a bit old

**Comment by raphodn** [comment]
ok to merge ? so that we can then : 
- have crowdin run the translations
- do another PR to add / fix the links to this page
- do a final PR to remove the ``/app` prefix :star_struck:

**Comment by raphodn** [comment]
French translation done here : #884

**Pull request merged**
